Project Setup
PythonBulawayo/ChitChat pull request #65
Opened 2024-10-05 20:41 UTC by TanyaMushonga

**Title:**  
Initial Project Setup with Theming, Typography, Folder Structure, and Navigation Bar

**Description:**  
This PR sets up the foundation for the open-source project by implementing key structural and UI elements. Below is a breakdown of the changes made:

- **Theming and Typography:**
  - Applied global themes, including color schemes, fonts, and base styles to ensure consistency across the project.
  - Configured typography for headings, paragraphs, and other text elements.

- **Project Folder Structure:**
  - Created an organized folder structure to promote scalability and maintainability.
  - Separated components, styles, assets, and pages to streamline development and future enhancements.

- **Navigation Bar:**
  - Designed and implemented a responsive navigation bar.
  - Linked navigation bar buttons to their respective pages.
  - Ensured the navigation bar is responsive across various screen sizes for a seamless user experience.

**Testing:**  
- Verified that the navigation bar functions correctly on both desktop and mobile.
- Ensured all linked pages are accessible through the navigation bar.
- Checked responsiveness on different device viewports.

**Next Steps:**  
- Future PRs will build upon this foundation, adding additional components and functionalities.

2024-10-05 20:46 UTC, terrameijar commented
@TanyaMushonga, thank you for setting this up. I'll take a close look at the PR soon. The PR is failing eslint check, could you please run eslint on your changes and ensure that there are no eslint errors?

2024-10-05 20:49 UTC, TanyaMushonga commented
Ok let me fix rhe eslint errors

2024-10-08 16:09 UTC, terrameijar requested changes
@TanyaMushonga thank you, this looks good so far. There only change I'll ask you to make is removing your picture from the project and using a fake avatar instead.

2024-10-09 19:27 UTC, TanyaMushonga commented on frontend/src/assets/profile.jpg
No problem let me work on it

2024-10-12 05:46 UTC, TanyaMushonga commented
@terrameijar  l have fixed the issue of placeholder profile picture

2024-10-13 15:34 UTC, TanyaMushonga commented
@terrameijar can you review and merge the changes that l have made

2024-10-13 20:15 UTC, terrameijar approved these changes
These changes look good. Thanks @TanyaMushonga !

2024-10-13 20:16 UTC, merged